#######################
# Luke Brown          #
# CPSC 1020 003, F16  #
# PA3                 #
# luke4@g.clemson.edu #
#######################
all: ./*.cpp
	g++ -Wall *.cpp -o WF2 -std=c++11
run: all
	./run input.txt
clean:
	rm run || rm *.o